install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host i686-pc-windows-msvc --profile minimal
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false
test_script:
  # We do not have libxcb and thus cannot build x11rb
  #- cargo build --verbose --all-targets
  - cargo test --verbose
