install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host i686-pc-windows-gnu --profile minimal
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

  - C:\cygwin\setup-x86.exe -qnNd -R "C:/Program Files/Git" -g -P libxcb-devel
  - set PATH=C:\msys64\mingw32\bin;C:\Program Files\Git\bin;%PATH%
  - set PKG_CONFIG_PATH=C:\Program Files\Git\lib\pkgconfig
    #- set RUSTFLAGS=-L "C:\Program Files\Git\lib"
  - pkg-config --modversion xcb
  - pkg-config --cflags --libs xcb

build: false
test_script:
  - cargo build --verbose --all-targets
  - cargo test --verbose
